POST http://0.0.0.0:5000/accounts/login
Content-Type:  application/json

{
     "studentId" : 11211,
     "email" : "varunjoshi426@gmail.com",
     "password"  : "varun"
}



####


POST http://0.0.0.0:5000/accounts/signup
Content-Type:  application/json

{
      "studentName" : "coders",
     "studentId" : 55155,
     "email" : "3coders33@gmail.com",
     "password"  : "12"
}



####

GET http://0.0.0.0:5000/votes/fetch-all-votes
